### ISSUE TITLE
Access denied for replica user repluser in replicas after scaling up

### ISSUE THREAD

**Issue by ernestom** [autopilotpattern/mysql#38]
After a `docker-compose scale mysql=3` I keep seeing the following error in the replicas:

```
mysql_3   | 2016-06-14 20:46:25,924 ERROR manage.py (1045, u"Access denied for user 'repluser'@'localhost' (using password: YES)")
mysql_3   | Traceback (most recent call last):
mysql_3   |   File "/usr/local/bin/manage.py", line 341, in health
mysql_3   |     node.conn = wait_for_connection(**ctx)
mysql_3   |   File "/usr/local/bin/manage.py", line 614, in wait_for_connection
mysql_3   |     connect_timeout=timeout)
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/__init__.py", line 88, in Connect
mysql_3   |     return Connection(*args, **kwargs)
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 657, in __init__
mysql_3   |     self.connect()
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 851, in connect
mysql_3   |     self._request_authentication()
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1034, in _request_authentication
mysql_3   |     auth_packet = self._read_packet()
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 906, in _read_packet
mysql_3   |     packet.check_error()
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 367, in check_error
mysql_3   |     err.raise_mysql_exception(self._data)
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 120, in raise_mysql_exception
mysql_3   |     _check_mysql_exception(errinfo)
mysql_3   |   File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 112, in _check_mysql_exception
mysql_3   |     raise errorclass(errno, errorvalue)
mysql_3   | OperationalError: (1045, u"Access denied for user 'repluser'@'localhost' (using password: YES)")
mysql_3   | 2016/06/14 20:46:25 exit status 1
``` 

In consul I just see _mysql-primary_, no replicas.

I tested this both locally and on Triton using a fresh clone of this repo.

**Comment by tgross** [comment]
That usually means that syncing the snapshot to Manta failed or that the keys for it weren't written to Consul. Things to check:
- do the `mysql-backup-run`, `mysql-last-backup` and `mysql-last-binlog` exist in the Consul K/V store?
- are there any Python stack traces in the primary instance's logs?

**Comment by ernestom** [comment]
Indeed it was the snapshot failing to sync due to an incorrect value in my _env file. I fixed it and everything works as expected now.

For the sake of completeness: those keys didn't exist in Consul, and the primary instance didn't show any python stack trace.

Thanks!
