### ISSUE TITLE
consul rpc error: invalid session

### ISSUE THREAD

**Issue by qujiaqi** [autopilotpattern/mysql#76]
Hi，
I have a question。 operation as follows：
containerpilot mysqld --console --log-bin=mysql-bin --log_slave_updates=ON --gtid-mode=ON --enforce-gtid-consistency=ON 
return question ：
```
consul.base.ConsulException: 500 rpc error: invalid session "5bbc14e3-4e7a-dc55-cc6d-76a7452a8de2"                                                                                
consul: RPC failed to server X.X.X.X:8300: rpc error: invalid session "5bbc14e3-4e7a-dc55-cc6d-76a7452a8de2"                                                                      
http: Request PUT /v1/kv/mysql-primary?acquire=5bbc14e3-4e7a-dc55-cc6d-76a7452a8de2, error: rpc error: invalid session "5bbc14e3-4e7a-dc55-cc6d-76a7452a8de2" from=127.0.0.1:47319

code position：
Traceback (most recent call last):                                             
  File "/usr/local/bin/manage.py", line 412, in <module>                       
    main()                                                                     
  File "/usr/local/bin/manage.py", line 409, in main                           
    cmd(node)                                                                  
  File "/usr/local/bin/manager/utils.py", line 64, in wrapper                  
    out = apply(fn, args, kwargs)                                              
  File "/usr/local/bin/manage.py", line 128, in health                         
    assert_initialized_for_state(node)                                         
  File "/usr/local/bin/manager/utils.py", line 64, in wrapper                  
    out = apply(fn, args, kwargs)                                              
  File "/usr/local/bin/manage.py", line 298, in assert_initialized_for_state   
    run_as_primary(node)                                                       
  File "/usr/local/bin/manager/utils.py", line 64, in wrapper                  
    out = apply(fn, args, kwargs)                                              
  File "/usr/local/bin/manage.py", line 340, in run_as_primary                 
    if not node.consul.mark_as_primary(node.name):                             
  File "/usr/local/bin/manager/utils.py", line 64, in wrapper                  
    out = apply(fn, args, kwargs)                                              
  File "/usr/local/bin/manager/libconsul.py", line 154, in mark_as_primary     
    if not self.lock(PRIMARY_KEY, name, session_id):                           
  File "/usr/local/bin/manager/utils.py", line 64, in wrapper                  
    out = apply(fn, args, kwargs)                                              
  File "/usr/local/bin/manager/libconsul.py", line 93, in lock                 
    return self.client.kv.put(key, value, acquire=session_id)                  
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 459, in pu
    '/v1/kv/%s' % key, params=params, data=value)                              
  File "/usr/local/lib/python2.7/dist-packages/consul/std.py", line 39, in put 
    self.session.put(uri, data=data, verify=self.verify)))                     
  File "/usr/local/lib/python2.7/dist-packages/consul/base.py", line 111, in cb
```

**Comment by tgross** [comment]
@qujiaqi when we try to mark the instance as primary, we're doing so with a Consul session. The session ID is cached on disk and eventually expires from Consul (but we don't need it again). The session ID this instance has is invalid, which means that the session ID has expired before it was used, or that we tried to bootstrap the cluster again without clearing data from Consul. Did you have a problem starting some of the instances originally?

**Comment by tgross** [comment]
@qujiaqi did you have any more on this?
